/* 収録エピソードと章の読み込みリスト。
 * 章を追加するときは、新しいフォルダを作ってここに id を1つ足すだけ。
 * fx:true を付けると、その章フォルダの effect.js も読み込みます。 */
window.EPISODE_MANIFEST = [
  {
    id: 'ep01',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
    ],
  },
  {
    id: 'ep02',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
    ],
  },
  {
    id: 'ep03',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
      { id: 'ch10', fx: true },
      { id: 'ch11', fx: true },
      { id: 'ch12', fx: true },
      { id: 'ch13', fx: true },
    ],
  },
  {
    id: 'ep04',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
    ],
  },
  {
    id: 'ep05',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
      { id: 'ch10', fx: true },
      { id: 'ch11', fx: true },
      { id: 'ch12', fx: true },
    ],
  },
  {
    id: 'ep06',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
    ],
  },
  {
    id: 'ep07',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
    ],
  },
  {
    id: 'ep08',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
      { id: 'ch10', fx: true },
      { id: 'ch11', fx: true },
      { id: 'ch12', fx: true },
      { id: 'ch13', fx: true },
    ],
  },
  {
    id: 'ep09',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
      { id: 'ch10', fx: true },
      { id: 'ch11', fx: true },
      { id: 'ch12', fx: true },
      { id: 'ch13', fx: true },
    ],
  },
  {
    id: 'ep10',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
      { id: 'ch10', fx: true },
      { id: 'ch11', fx: true },
      { id: 'ch12', fx: true },
      { id: 'ch13', fx: true },
    ],
  },
  {
    id: 'ep11',
    chapters: [
      { id: 'ch01', fx: true },
      { id: 'ch02', fx: true },
      { id: 'ch03', fx: true },
      { id: 'ch04', fx: true },
      { id: 'ch05', fx: true },
      { id: 'ch06', fx: true },
      { id: 'ch07', fx: true },
      { id: 'ch08', fx: true },
      { id: 'ch09', fx: true },
      { id: 'ch10', fx: true },
      { id: 'ch11', fx: true },
      { id: 'ch12', fx: true },
    ],
  },
];
